const T={
pt:{navBooks:"Livros",navAuthor:"Autor",navReaders:"Leitores",eyebrow:"LITERATURA • DESEJO • LIBERDADE",heroTitle:"Há coisas que escondemos dos outros. E há aquelas que escondemos de nós mesmos.",heroLead:"Histórias sobre amor, desejo, liberdade e as escolhas que fazemos quando aquilo que sentimos já não cabe na vida que construímos.",discover:"Descubra qual história vai encontrar você",whatsapp:"Falar pelo WhatsApp",heroQuote:"Todo desejo carrega, em si, um convite à liberdade.",works:"OBRAS",booksTitle:"Livros",novel:"ROMANCE",linhaDesc:"E se o amor não acabasse — mas a maneira de amar deixasse de funcionar? Augusto e Helena construíram uma vida sólida, até que uma fissura quase imperceptível começa a atravessar tudo. Entre Brasília e Pequim, desejo, liberdade e pertencimento deixam de ser ideias abstratas e se transformam em escolhas. Algumas relações terminam. Outras precisam ser reinventadas. Qual das duas coisas está acontecendo com eles?",buyPt:"Comprar na Amazon",buyLinha:"Quero ler Linha Invisível",buyGeo:"Quero entrar nessas histórias",buyLinea:"Quiero descubrir Línea Invisible",spanishEdition:"Edição em espanhol →",stories:"CONTOS",geoDesc:"Quanto de nós permanece escondido apenas porque nunca encontramos liberdade suficiente para revelar? Há desejos que começam no corpo. Outros começam muito antes — numa ausência, numa memória, numa pergunta que passamos anos evitando. Estas não são histórias sobre transgressão. São histórias sobre aquilo que descobrimos quando já não conseguimos mentir para nós mesmos.",aboutLabel:"O AUTOR",bio:"Escritor brasileiro, Júlio Rocha transita entre a literatura, a comunicação e o Direito. Em sua ficção, investiga relações humanas, liberdade, desejo e os territórios nem sempre visíveis que separam aquilo que somos daquilo que ousamos viver.",readersLabel:"VOZES DE QUEM LEU",readersTitle:"Leitores",readersIntro:"Este espaço será destinado às impressões dos leitores. A versão publicada poderá receber comentários compartilhados e moderados.",yourName:"Seu nome",yourComment:"Seu comentário",sendComment:"Enviar comentário",commentNotice:"Demonstração: o envio público será ativado na publicação, com moderação anti-spam.",spanishNovel:"EDIÇÃO EM ESPANHOL",lineaDesc:"¿Qué ocurre cuando el amor permanece, pero las reglas que lo sostenían comienzan a romperse? Hay grietas que destruyen. Y hay otras por las que, inesperadamente, entra la vida. A veces, la verdadera pregunta no es a quién amamos, sino quiénes nos permitimos ser cuando amamos.",buyAmazon:"Comprar na Amazon",footer:"Literatura, desejo e liberdade."},
es:{navBooks:"Libros",navAuthor:"Autor",navReaders:"Lectores",eyebrow:"LITERATURA • DESEO • LIBERTAD",heroTitle:"Hay cosas que ocultamos a los demás. Y otras que ocultamos de nosotros mismos.",heroLead:"Historias sobre amor, deseo, libertad y las decisiones que tomamos cuando lo que sentimos ya no cabe en la vida que hemos construido.",discover:"Descubre qué historia te encontrará",whatsapp:"Hablar por WhatsApp",heroQuote:"Todo deseo lleva consigo una invitación a la libertad.",works:"OBRAS",booksTitle:"Libros",novel:"NOVELA",linhaDesc:"¿Y si el amor no terminara, pero la manera de amar dejara de funcionar? Augusto y Helena construyeron una vida sólida, hasta que una grieta casi imperceptible comienza a atravesarlo todo. Entre Brasilia y Pekín, deseo, libertad y pertenencia se convierten en decisiones. Algunas relaciones terminan. Otras necesitan reinventarse. ¿Qué está ocurriendo con ellos?",buyPt:"Comprar en Amazon",buyLinha:"Quiero leer Linha Invisível",buyGeo:"Quiero entrar en estas historias",buyLinea:"Quiero descubrir Línea Invisible",spanishEdition:"Edición en español →",stories:"CUENTOS",geoDesc:"¿Cuánto de nosotros permanece oculto porque nunca encontramos suficiente libertad para revelarlo? Hay deseos que comienzan en el cuerpo. Otros empiezan mucho antes: en una ausencia, un recuerdo, una pregunta que llevamos años evitando. No son historias sobre transgresión. Son historias sobre lo que descubrimos cuando ya no podemos mentirnos a nosotros mismos.",aboutLabel:"EL AUTOR",bio:"Escritor brasileño, Júlio Rocha transita entre la literatura, la comunicación y el Derecho. En su ficción investiga las relaciones humanas, la libertad, el deseo y los territorios no siempre visibles que separan lo que somos de aquello que nos atrevemos a vivir.",readersLabel:"VOCES DE QUIENES LEYERON",readersTitle:"Lectores",readersIntro:"Este espacio estará dedicado a las impresiones de los lectores. La versión publicada podrá recibir comentarios compartidos y moderados.",yourName:"Tu nombre",yourComment:"Tu comentario",sendComment:"Enviar comentario",commentNotice:"Demostración: el envío público se activará al publicar el sitio, con moderación antispam.",spanishNovel:"EDICIÓN EN ESPAÑOL",lineaDesc:"¿Qué ocurre cuando el amor permanece, pero las reglas que lo sostenían comienzan a romperse? Hay grietas que destruyen. Y hay otras por las que, inesperadamente, entra la vida. A veces, la verdadera pregunta no es a quién amamos, sino quiénes nos permitimos ser cuando amamos.",buyAmazon:"Comprar en Amazon",footer:"Literatura, deseo y libertad."},
en:{navBooks:"Books",navAuthor:"Author",navReaders:"Readers",eyebrow:"LITERATURE • DESIRE • FREEDOM",heroTitle:"There are things we hide from others. And things we hide from ourselves.",heroLead:"Stories about love, desire, freedom, and the choices we make when what we feel no longer fits the life we have built.",discover:"Discover which story will find you",whatsapp:"Chat on WhatsApp",heroQuote:"Every desire carries within it an invitation to freedom.",works:"WORKS",booksTitle:"Books",novel:"NOVEL",linhaDesc:"What if love did not end, but the way of loving stopped working? Augusto and Helena built a solid life, until an almost imperceptible crack begins to run through everything. Between Brasília and Beijing, desire, freedom and belonging become choices. Some relationships end. Others must be reinvented. Which is happening to them?",buyPt:"Buy on Amazon",buyLinha:"I want to read Linha Invisível",buyGeo:"I want to enter these stories",buyLinea:"Discover Línea Invisible",spanishEdition:"Spanish edition →",stories:"SHORT STORIES",geoDesc:"How much of us remains hidden simply because we have never found enough freedom to reveal it? Some desires begin in the body. Others begin much earlier—in an absence, a memory, a question we have spent years avoiding. These are not stories about transgression. They are stories about what we discover when we can no longer lie to ourselves.",aboutLabel:"THE AUTHOR",bio:"Brazilian writer Júlio Rocha moves between literature, communication and law. His fiction explores human relationships, freedom, desire and the often invisible territories separating who we are from what we dare to live.",readersLabel:"READERS' VOICES",readersTitle:"Readers",readersIntro:"This space is intended for readers' impressions. The published version can receive shared, moderated comments.",yourName:"Your name",yourComment:"Your comment",sendComment:"Post comment",commentNotice:"Demo: public posting will be enabled when the site is published, with anti-spam moderation.",spanishNovel:"SPANISH EDITION",lineaDesc:"What happens when love remains, but the rules that sustained it begin to break? Some cracks destroy. Through others, unexpectedly, life enters. Sometimes the real question is not whom we love, but who we allow ourselves to become when we love.",buyAmazon:"Buy on Amazon",footer:"Literature, desire and freedom."}
};
function setLang(l){document.documentElement.lang=l==="pt"?"pt-BR":l;document.querySelectorAll("[data-i18n]").forEach(e=>{const k=e.dataset.i18n;if(T[l][k])e.textContent=T[l][k]});document.querySelectorAll(".lang").forEach(b=>b.classList.toggle("active",b.dataset.lang===l));localStorage.setItem("jr-lang",l)}
document.querySelectorAll(".lang").forEach(b=>b.onclick=()=>setLang(b.dataset.lang));
setLang(localStorage.getItem("jr-lang")||"pt");
document.getElementById("commentBtn").onclick=()=>{document.getElementById("commentNotice").textContent={pt:"A interface está pronta. Antes de publicar, conectaremos o formulário a um serviço gratuito com moderação.",es:"La interfaz está lista. Antes de publicar, conectaremos el formulario a un servicio gratuito con moderación.",en:"The interface is ready. Before publishing, we will connect the form to a free moderated service."}[localStorage.getItem("jr-lang")||"pt"]};

const BIO={
pt:{readMore:"Leia mais",readLess:"Recolher",bioFull:`<p>Júlio Rocha nasceu em Porto Alegre, mas há muito deixou de acreditar que pertencemos a um único lugar. Ao longo da vida, percorreu cidades do Brasil, da Europa e da América Latina, acumulando não apenas geografias, mas histórias, silêncios e perguntas. Hoje vive em Brasília, cidade cuja arquitetura, contradições e horizontes atravessam parte de sua obra.</p><div class="bio-extra"><p>Romancista e contista, dedica-se à exploração dos territórios invisíveis da experiência humana: amor, desejo, liberdade, identidade, pertencimento e transformação. Seus livros investigam aquilo que acontece quando as formas tradicionais já não conseguem conter a complexidade dos afetos contemporâneos.</p><p>É autor do romance <em>Linha Invisível</em> e da coletânea de contos <em>Geografia dos Desejos</em>, obras que compartilham uma mesma inquietação literária: compreender como homens e mulheres negociam amor, liberdade e verdade em um mundo marcado por mudanças constantes. Seus personagens raramente enfrentam grandes vilões externos; enfrentam, sobretudo, as tensões entre aquilo que sentem, aquilo que desejam e aquilo que aprenderam a ser.</p><p>Com estudos em Filosofia, Jornalismo e Direito, transita com naturalidade entre reflexão e emoção, razão e corpo, pensamento e experiência. Sua escrita combina observação psicológica, densidade simbólica e forte presença sensorial, explorando as zonas de sombra onde convivem ternura, desejo, medo e descoberta.</p><p>Em suas narrativas, o erotismo não surge como provocação gratuita, mas como linguagem humana: uma forma de revelar conflitos, vulnerabilidades e buscas por autenticidade. Seus personagens são livres, imperfeitos e profundamente humanos; pessoas que erram sem deixar de amar e que descobrem, muitas vezes, que a liberdade não é ausência de vínculos, mas a coragem de escolhê-los conscientemente.</p><p>Júlio acredita que a literatura não existe para oferecer respostas definitivas, mas para iluminar perguntas que raramente fazemos em voz alta. Quando não está escrevendo, continua fazendo aquilo que sempre alimentou sua ficção: observando cidades, ouvindo histórias e tentando compreender o que existe por trás das aparências.</p></div>`},
es:{readMore:"Leer más",readLess:"Cerrar",bioFull:`<p>Júlio Rocha nació en Porto Alegre, pero hace mucho dejó de creer que pertenecemos a un solo lugar. A lo largo de su vida recorrió ciudades de Brasil, Europa y América Latina, acumulando no solo geografías, sino historias, silencios y preguntas. Hoy vive en Brasilia, ciudad cuya arquitectura, contradicciones y horizontes atraviesan parte de su obra.</p><div class="bio-extra"><p>Novelista y cuentista, se dedica a explorar los territorios invisibles de la experiencia humana: amor, deseo, libertad, identidad, pertenencia y transformación. Sus libros investigan lo que sucede cuando las formas tradicionales ya no consiguen contener la complejidad de los afectos contemporáneos.</p><p>Es autor de la novela <em>Linha Invisível</em> y de la colección de cuentos <em>Geografia dos Desejos</em>, obras que comparten una misma inquietud literaria: comprender cómo hombres y mujeres negocian amor, libertad y verdad en un mundo marcado por cambios constantes. Sus personajes rara vez se enfrentan a grandes villanos externos; se enfrentan, sobre todo, a las tensiones entre lo que sienten, lo que desean y lo que aprendieron a ser.</p><p>Con estudios en Filosofía, Periodismo y Derecho, transita con naturalidad entre reflexión y emoción, razón y cuerpo, pensamiento y experiencia. Su escritura combina observación psicológica, densidad simbólica y una fuerte presencia sensorial, explorando las zonas de sombra donde conviven ternura, deseo, miedo y descubrimiento.</p><p>En sus narraciones, el erotismo no aparece como provocación gratuita, sino como lenguaje humano: una forma de revelar conflictos, vulnerabilidades y búsquedas de autenticidad. Sus personajes son libres, imperfectos y profundamente humanos; personas que se equivocan sin dejar de amar y que descubren, muchas veces, que la libertad no es ausencia de vínculos, sino el valor de elegirlos conscientemente.</p><p>Júlio cree que la literatura no existe para ofrecer respuestas definitivas, sino para iluminar preguntas que rara vez hacemos en voz alta. Cuando no escribe, continúa haciendo aquello que siempre alimentó su ficción: observar ciudades, escuchar historias e intentar comprender lo que existe detrás de las apariencias.</p></div>`},
en:{readMore:"Read more",readLess:"Show less",bioFull:`<p>Júlio Rocha was born in Porto Alegre, but long ago stopped believing that we belong to a single place. Throughout his life, he has traveled through cities in Brazil, Europe and Latin America, gathering not only geographies but stories, silences and questions. He now lives in Brasília, a city whose architecture, contradictions and horizons run through part of his work.</p><div class="bio-extra"><p>A novelist and short-story writer, he explores the invisible territories of human experience: love, desire, freedom, identity, belonging and transformation. His books examine what happens when traditional forms can no longer contain the complexity of contemporary affections.</p><p>He is the author of the novel <em>Linha Invisível</em> and the short-story collection <em>Geografia dos Desejos</em>, works united by the same literary concern: understanding how men and women negotiate love, freedom and truth in a world marked by constant change. His characters rarely confront great external villains; above all, they confront the tensions between what they feel, what they desire and what they have learned to be.</p><p>With studies in Philosophy, Journalism and Law, he moves naturally between reflection and emotion, reason and body, thought and experience. His writing combines psychological observation, symbolic density and a strong sensory presence, exploring shadowed areas where tenderness, desire, fear and discovery coexist.</p><p>In his narratives, eroticism does not appear as gratuitous provocation, but as a human language: a way of revealing conflicts, vulnerabilities and searches for authenticity. His characters are free, imperfect and deeply human; people who make mistakes without ceasing to love and who often discover that freedom is not the absence of bonds, but the courage to choose them consciously.</p><p>Júlio believes literature does not exist to offer definitive answers, but to illuminate questions we rarely ask aloud. When he is not writing, he continues doing what has always nourished his fiction: observing cities, listening to stories and trying to understand what lies behind appearances.</p></div>`}
};
let bioExpanded=false;
const originalSetLang=setLang;
setLang=function(l){originalSetLang(l);const b=BIO[l]||BIO.pt;document.getElementById("bioText").innerHTML=b.bioFull;document.querySelector(".author-text").classList.toggle("expanded",bioExpanded);document.getElementById("bioToggle").textContent=bioExpanded?b.readLess:b.readMore;}
document.getElementById("bioToggle").onclick=()=>{bioExpanded=!bioExpanded;setLang(localStorage.getItem("jr-lang")||"pt")};
setLang(localStorage.getItem("jr-lang")||"pt");

document.querySelectorAll(".sample-toggle").forEach(btn=>{
 btn.addEventListener("click",()=>{
   const el=document.getElementById(btn.dataset.target);
   const open=el.classList.toggle("open");
   const l=localStorage.getItem("jr-lang")||"pt";
   const labels={pt:["Leia um fragmento →","Recolher ↑"],es:["Lee un fragmento →","Cerrar ↑"],en:["Read an excerpt →","Close ↑"]};
   btn.textContent=labels[l][open?1:0];
 });
});

const mobileBuy=document.getElementById("mobileBuy");
if(mobileBuy){
 const targets=[
  {el:document.getElementById("linha-invisivel"),url:"https://www.amazon.com.br/dp/B0GQD4GR5S"},
  {el:document.getElementById("geografia-dos-desejos"),url:"https://www.amazon.com.br/dp/B0GPY9S4JM"}
 ];
 window.addEventListener("scroll",()=>{
   let best=targets[0],dist=Infinity;
   targets.forEach(t=>{if(t.el){const d=Math.abs(t.el.getBoundingClientRect().top-160);if(d<dist){dist=d;best=t}}});
   mobileBuy.href=best.url;
 },{passive:true});
}
